### PR TITLE
tweaked sql query in log func to avoid sql injections

### PR DESCRIPTION
**Pull request by kedaroo**
Thanks for creating this repo. It's a great way for beginners to start working with databases.

### CODE REVIEW

**Review by SouravJohar — APPROVED** [review]
Nice, I hadn't though of that. If you could, maybe a small write up of how the older commit could lead to injections would be helpful to people.

**Comment by kedaroo** [comment]
Sure. I'll try

**Comment by kedaroo** [comment]
Check out this xkcd comic about sql injection that you might find funny.
https://xkcd.com/327/

**Comment by SouravJohar** [comment]
Hehe, nice. I enjoy programming humor.
So what are you doing currently? Student or Work?

**Comment by kedaroo** [comment]
Student.

**Pull request merged**
